kind: Deployment
apiVersion: apps/v1
metadata:
  name: train-schedule
  labels:
    app: train-schedule
spec:
  replicas: 4
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: pksharathkumar/train-schedule:bno
        ports:
        - name: http
          containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: train-schedule
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30003
